apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: unzip-and-ingest
build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/unzip-and-ingest
    jib: {}
  tagPolicy:
    gitCommit: {}
# deploy:
#  kubectl:
#    manifests:
#    - k8s-prod.yml

deploy:
  helm:
    releases:
    - name: unzip-and-ingest
      chartPath: charts
      valuesFiles: 
        - charts/values-3pa.yaml

