apiVersion: v2
appVersion: 1.0.0-RC2
description: A lightweight integration platform, born on Kubernetes, with serverless
  superpowers
home: https://camel.apache.org/camel-k/latest/
icon: https://github.com/apache/camel/raw/master/docs/img/logo64-d.png
keywords:
- serverless
- integration
- patterns
maintainers:
- email: nferraro@apache.org
  name: nferraro
name: camel-k
sources:
- https://github.com/apache/camel-k
- https://github.com/apache/camel-k-runtime
- https://github.com/apache/camel-quarkus
- https://github.com/apache/camel
type: application
version: 0.2.1
