apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: unzip-and-ingest
build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/unzip-and-ingest
    jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
    - name: unzip-and-ingest
      chartPath: charts

