apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: skysat-processing
build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/skysat-processing
    jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - k8s.yml
