apiVersion: v1
data:
  settings.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
      <localRepository></localRepository>
      <profiles>
        <profile>
          <id>maven-settings</id>
          <activation>
            <activeByDefault>true</activeByDefault>
          </activation>
          <repositories>
            <repository>
              <id>central</id>
              <url>https://repo.maven.apache.org/maven2</url>
              <snapshots>
                <enabled>false</enabled>
                <checksumPolicy>fail</checksumPolicy>
              </snapshots>
              <releases>
                <enabled>true</enabled>
                <checksumPolicy>fail</checksumPolicy>
              </releases>
            </repository>
          </repositories>
          <pluginRepositories>
            <pluginRepository>
              <id>central</id>
              <url>https://repo.maven.apache.org/maven2</url>
              <snapshots>
                <enabled>false</enabled>
                <checksumPolicy>fail</checksumPolicy>
              </snapshots>
              <releases>
                <enabled>true</enabled>
                <checksumPolicy>fail</checksumPolicy>
              </releases>
            </pluginRepository>
          </pluginRepositories>
        </profile>
      </profiles>
    </settings>
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: camel-k
  name: camel-k-maven-settings
  selfLink: /api/v1/namespaces/omar-dev/configmaps/camel-k-maven-settings
