apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: 3pa-unzip-and-ingest
build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/3pa-unzip-and-ingest
    jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - k8s.yml

# HELM DEPLOYMENT CONFIGURATION
# apiVersion: skaffold/v2beta5
# kind: Config
# metadata:
#   name: 3pa-unzip-and-ingest
# build:
#   artifacts:
#   - image: nexus-docker-public-hosted.ossim.io/3pa-unzip-and-ingest
#     jib: {}
#   tagPolicy:
#     gitCommit: {}
# deploy:
#   helm:
#     releases:
#     - name: 3pa-unzip-and-ingest
#       chartPath: charts
