apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: gegd-processing
build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/gegd-processing
    jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - k8s.yml